//
// ActivityEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ActivityEvent: Codable, JSONEncodable, Hashable {

    public var event: String?
    public var time: String?
    public var collectionId: String?
    public var deviceId: String?
    public var gatewayId: String?
    public var data: [String: String]?

    public init(event: String? = nil, time: String? = nil, collectionId: String? = nil, deviceId: String? = nil, gatewayId: String? = nil, data: [String: String]? = nil) {
        self.event = event
        self.time = time
        self.collectionId = collectionId
        self.deviceId = deviceId
        self.gatewayId = gatewayId
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case event
        case time
        case collectionId
        case deviceId
        case gatewayId
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(event, forKey: .event)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(gatewayId, forKey: .gatewayId)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

