//
// AddDownstreamMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is the request object to send messages out to the devices */
public struct AddDownstreamMessageRequest: Codable, JSONEncodable, Hashable {

    public var payload: Data?

    public init(payload: Data? = nil) {
        self.payload = payload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case payload
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(payload, forKey: .payload)
    }
}

