//
// AssignTargetImageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response object when assigning an image to a collection or collection/device */
public struct AssignTargetImageResponse: Codable, JSONEncodable, Hashable {

    public var collectionId: String?
    public var imageId: String?
    public var deviceId: String?

    public init(collectionId: String? = nil, imageId: String? = nil, deviceId: String? = nil) {
        self.collectionId = collectionId
        self.imageId = imageId
        self.deviceId = deviceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionId
        case imageId
        case deviceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(imageId, forKey: .imageId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
    }
}

