//
// BlobStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Statistics for a single blob */
public struct BlobStats: Codable, JSONEncodable, Hashable {

    public var blobBytesMb: Float?

    public init(blobBytesMb: Float? = nil) {
        self.blobBytesMb = blobBytesMb
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blobBytesMb
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(blobBytesMb, forKey: .blobBytesMb)
    }
}

