//
// BlobStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Statistics for a single blob */
public struct BlobStats: Codable, JSONEncodable, Hashable {

    public var blobBytes: String?

    public init(blobBytes: String? = nil) {
        self.blobBytes = blobBytes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blobBytes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(blobBytes, forKey: .blobBytes)
    }
}

