//
// BroadcastMessageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BroadcastMessageRequest: Codable {

    public var collectionId: String?
    public var port: Int?
    public var payload: Data?
    /** Valid transports are \&quot;udp\&quot;, \&quot;coap\&quot;, \&quot;coap-pull\&quot;, \&quot;udp-pull\&quot;, \&quot;coap-push\&quot;, \&quot;udp-push\&quot;. \&quot;udp\&quot; is equivalent to \&quot;udp-push\&quot; and \&quot;coap\&quot; is equivalent to \&quot;coap-push\&quot;. Push messages are sent unsolicited to the device wheil pull messages are sent whenever the device wither sends data upstream (for UDP) or does a CoAP request to the CoAP service in span. */
    public var transport: String?
    public var coapPath: String?

    public init(collectionId: String? = nil, port: Int? = nil, payload: Data? = nil, transport: String? = nil, coapPath: String? = nil) {
        self.collectionId = collectionId
        self.port = port
        self.payload = payload
        self.transport = transport
        self.coapPath = coapPath
    }

}
