//
// CellularIoTConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is the cellular IOT config */
public struct CellularIoTConfig: Codable, JSONEncodable, Hashable {

    public var imsi: String?
    public var imei: String?

    public init(imsi: String? = nil, imei: String? = nil) {
        self.imsi = imsi
        self.imei = imei
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imsi
        case imei
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imsi, forKey: .imsi)
        try container.encodeIfPresent(imei, forKey: .imei)
    }
}

