//
// CertificateInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Certificate information */
public struct CertificateInfo: Codable, JSONEncodable, Hashable {

    public var certificateSerial: String?
    public var expires: String?

    public init(certificateSerial: String? = nil, expires: String? = nil) {
        self.certificateSerial = certificateSerial
        self.expires = expires
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case certificateSerial
        case expires
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(certificateSerial, forKey: .certificateSerial)
        try container.encodeIfPresent(expires, forKey: .expires)
    }
}

