//
// ClearFirmwareErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClearFirmwareErrorResponse: Codable {

    public var result: String?

    public init(result: String? = nil) {
        self.result = result
    }

}
