//
// CoAPMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CoAPMetadata: Codable {

    public var code: String?
    public var path: String?

    public init(code: String? = nil, path: String? = nil) {
        self.code = code
        self.path = path
    }

}
