//
// CollectionFirmware.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CollectionFirmware: Codable {

    /** The current firmware is the firmware that the devices are currently using. */
    public var currentFirmwareId: String?
    /** The target firmware is set to the desired firmware image for the devices in this collection. If the management is set to \&quot;device\&quot; this will only be used if the target firmware isn&#39;t set on the device itself. */
    public var targetFirmwareId: String?
    public var management: CollectionFirmwareFirmwareManagement?

    public init(currentFirmwareId: String? = nil, targetFirmwareId: String? = nil, management: CollectionFirmwareFirmwareManagement? = nil) {
        self.currentFirmwareId = currentFirmwareId
        self.targetFirmwareId = targetFirmwareId
        self.management = management
    }

}
