//
// CreateCertificateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response when creating a new certificate */
public struct CreateCertificateResponse: Codable, JSONEncodable, Hashable {

    public var certificate: Data?
    public var privateKey: Data?
    public var chain: Data?

    public init(certificate: Data? = nil, privateKey: Data? = nil, chain: Data? = nil) {
        self.certificate = certificate
        self.privateKey = privateKey
        self.chain = chain
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case certificate
        case privateKey
        case chain
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(certificate, forKey: .certificate)
        try container.encodeIfPresent(privateKey, forKey: .privateKey)
        try container.encodeIfPresent(chain, forKey: .chain)
    }
}

