//
// CreateCertificateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request object to create a new certificate. */
public struct CreateCertificateRequest: Codable, JSONEncodable, Hashable {

    public var gatewayId: String?
    public var deviceId: String?

    public init(gatewayId: String? = nil, deviceId: String? = nil) {
        self.gatewayId = gatewayId
        self.deviceId = deviceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gatewayId
        case deviceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gatewayId, forKey: .gatewayId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
    }
}

