//
// CreateFirmwareRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateFirmwareRequest: Codable {

    public var collectionId: String?
    public var image: Data?
    public var version: String?
    public var filename: String?
    public var tags: [String: String]?

    public init(collectionId: String? = nil, image: Data? = nil, version: String? = nil, filename: String? = nil, tags: [String: String]? = nil) {
        self.collectionId = collectionId
        self.image = image
        self.version = version
        self.filename = filename
        self.tags = tags
    }

}
