//
// CreateLabeledFirmwareResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response object when creating a labeled firmware image */
public struct CreateLabeledFirmwareResponse: Codable, JSONEncodable, Hashable {

    public var image: LabeledFirmware?

    public init(image: LabeledFirmware? = nil) {
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(image, forKey: .image)
    }
}

