//
// CreateCollectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request object when creating a collection. The collect ID is assigned by the service. */
public struct CreateCollectionRequest: Codable, JSONEncodable, Hashable {

    /** The team ID that owns the collection. This field is required. When you create new collections the default is to use your private team ID. */
    public var teamId: String?
    public var firmware: CollectionFirmware?
    /** Tags for the collection. Tags are metadata fields that you can assign to the collection. */
    public var tags: [String: String]?

    public init(teamId: String? = nil, firmware: CollectionFirmware? = nil, tags: [String: String]? = nil) {
        self.teamId = teamId
        self.firmware = firmware
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case teamId
        case firmware
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(teamId, forKey: .teamId)
        try container.encodeIfPresent(firmware, forKey: .firmware)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

