//
// DeleteDownstreamMessageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response object when deleting a downstream message */
public struct DeleteDownstreamMessageResponse: Codable, JSONEncodable, Hashable {

    public var messageId: String?

    public init(messageId: String? = nil) {
        self.messageId = messageId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messageId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(messageId, forKey: .messageId)
    }
}

