//
// DeviceMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is the metadata for devices. */
public struct DeviceMetadata: Codable, JSONEncodable, Hashable {

    public var ciot: CellularIoTMetadata?
    public var inet: InetMetadata?
    public var gateway: GatewayDeviceMetadata?

    public init(ciot: CellularIoTMetadata? = nil, inet: InetMetadata? = nil, gateway: GatewayDeviceMetadata? = nil) {
        self.ciot = ciot
        self.inet = inet
        self.gateway = gateway
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ciot
        case inet
        case gateway
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ciot, forKey: .ciot)
        try container.encodeIfPresent(inet, forKey: .inet)
        try container.encodeIfPresent(gateway, forKey: .gateway)
    }
}

