//
// DeviceStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is the statistics for a single device */
public struct DeviceStats: Codable, JSONEncodable, Hashable {

    public var bytesUpstream: String?
    public var bytesDownstream: String?
    public var messagesUpstream: String?
    public var messagesDownstream: String?
    public var sessionCount: Int?

    public init(bytesUpstream: String? = nil, bytesDownstream: String? = nil, messagesUpstream: String? = nil, messagesDownstream: String? = nil, sessionCount: Int? = nil) {
        self.bytesUpstream = bytesUpstream
        self.bytesDownstream = bytesDownstream
        self.messagesUpstream = messagesUpstream
        self.messagesDownstream = messagesDownstream
        self.sessionCount = sessionCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bytesUpstream
        case bytesDownstream
        case messagesUpstream
        case messagesDownstream
        case sessionCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bytesUpstream, forKey: .bytesUpstream)
        try container.encodeIfPresent(bytesDownstream, forKey: .bytesDownstream)
        try container.encodeIfPresent(messagesUpstream, forKey: .messagesUpstream)
        try container.encodeIfPresent(messagesDownstream, forKey: .messagesDownstream)
        try container.encodeIfPresent(sessionCount, forKey: .sessionCount)
    }
}

