//
// Device.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Device: Codable {

    /** The device ID is assigned by the backend. */
    public var deviceId: String?
    public var collectionId: String?
    /** The IMSI is the unique ID for the (e|nu|whatever)SIM card on your device. This is the primary identifier for your device on the network. */
    public var imsi: String?
    /** The IMEI number is the unique ID for your hardware as seen by the network. Obviously you might have a completely different view on things. */
    public var imei: String?
    /** Tags are metadata for the device that you can set. These are just strings. */
    public var tags: [String: String]?
    public var network: NetworkMetadata?
    public var firmware: FirmwareMetadata?

    public init(deviceId: String? = nil, collectionId: String? = nil, imsi: String? = nil, imei: String? = nil, tags: [String: String]? = nil, network: NetworkMetadata? = nil, firmware: FirmwareMetadata? = nil) {
        self.deviceId = deviceId
        self.collectionId = collectionId
        self.imsi = imsi
        self.imei = imei
        self.tags = tags
        self.network = network
        self.firmware = firmware
    }

}
