//
// DumpedCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DumpedCollection: Codable {

    public var collection: Collection?
    public var devices: [DumpedDevice]?
    public var outputs: [Output]?

    public init(collection: Collection? = nil, devices: [DumpedDevice]? = nil, outputs: [Output]? = nil) {
        self.collection = collection
        self.devices = devices
        self.outputs = outputs
    }

}
