//
// DumpedDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DumpedDevice: Codable {

    public var device: Device?

    public init(device: Device? = nil) {
        self.device = device
    }

}
