//
// FieldMask.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FieldMask: Codable {

    public var imsi: Bool?
    public var imei: Bool?
    public var msisdn: Bool?
    public var location: Bool?

    public init(imsi: Bool? = nil, imei: Bool? = nil, msisdn: Bool? = nil, location: Bool? = nil) {
        self.imsi = imsi
        self.imei = imei
        self.msisdn = msisdn
        self.location = location
    }

}
