//
// FirmwareMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Metadata about firmware on devices. */
public struct FirmwareMetadata: Codable {

    public var currentFirmwareId: String?
    public var targetFirmwareId: String?
    /** Last reported firmware version. */
    public var firmwareVersion: String?
    public var serialNumber: String?
    public var modelNumber: String?
    public var manufacturer: String?
    /** State of the firmware. */
    public var state: String?
    public var stateMessage: String?

    public init(currentFirmwareId: String? = nil, targetFirmwareId: String? = nil, firmwareVersion: String? = nil, serialNumber: String? = nil, modelNumber: String? = nil, manufacturer: String? = nil, state: String? = nil, stateMessage: String? = nil) {
        self.currentFirmwareId = currentFirmwareId
        self.targetFirmwareId = targetFirmwareId
        self.firmwareVersion = firmwareVersion
        self.serialNumber = serialNumber
        self.modelNumber = modelNumber
        self.manufacturer = manufacturer
        self.state = state
        self.stateMessage = stateMessage
    }

}
