//
// FirmwareStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Statistics for a single firmware image */
public struct FirmwareStats: Codable, JSONEncodable, Hashable {

    public var firmwareImageSize: Int?

    public init(firmwareImageSize: Int? = nil) {
        self.firmwareImageSize = firmwareImageSize
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case firmwareImageSize
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(firmwareImageSize, forKey: .firmwareImageSize)
    }
}

