//
// FirmwareUsageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FirmwareUsageResponse: Codable {

    public var imageId: String?
    public var targeted: [String]?
    public var current: [String]?

    public init(imageId: String? = nil, targeted: [String]? = nil, current: [String]? = nil) {
        self.imageId = imageId
        self.targeted = targeted
        self.current = current
    }

}
