//
// FirmwareUsageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Firmware usage report */
public struct FirmwareUsageResponse: Codable, JSONEncodable, Hashable {

    public var imageId: String?
    public var targeted: [String]?
    public var current: [String]?

    public init(imageId: String? = nil, targeted: [String]? = nil, current: [String]? = nil) {
        self.imageId = imageId
        self.targeted = targeted
        self.current = current
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageId
        case targeted
        case current
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imageId, forKey: .imageId)
        try container.encodeIfPresent(targeted, forKey: .targeted)
        try container.encodeIfPresent(current, forKey: .current)
    }
}

