//
// GatewayConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GatewayConfig: Codable, JSONEncodable, Hashable {

    public var ciot: GatewayCIoTConfig?
    public var inet: GatewayInetConfig?
    public var user: GatewayCustomConfig?

    public init(ciot: GatewayCIoTConfig? = nil, inet: GatewayInetConfig? = nil, user: GatewayCustomConfig? = nil) {
        self.ciot = ciot
        self.inet = inet
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ciot
        case inet
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ciot, forKey: .ciot)
        try container.encodeIfPresent(inet, forKey: .inet)
        try container.encodeIfPresent(user, forKey: .user)
    }
}

