//
// GatewayStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GatewayStatus: String, Codable, CaseIterable {
    case unknown = "unknown"
    case offline = "offline"
    case online = "online"
}
