//
// GatewayDeviceMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Metadata for devices connected via user-managed gateways. This metadata shows the configuration for the last message transmission */
public struct GatewayDeviceMetadata: Codable, JSONEncodable, Hashable {

    public var gatewayId: String?
    public var lastUpdate: String?
    public var params: [String: String]?

    public init(gatewayId: String? = nil, lastUpdate: String? = nil, params: [String: String]? = nil) {
        self.gatewayId = gatewayId
        self.lastUpdate = lastUpdate
        self.params = params
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gatewayId
        case lastUpdate
        case params
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gatewayId, forKey: .gatewayId)
        try container.encodeIfPresent(lastUpdate, forKey: .lastUpdate)
        try container.encodeIfPresent(params, forKey: .params)
    }
}

