//
// GatewayCustomConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GatewayCustomConfig: Codable, JSONEncodable, Hashable {

    public var params: [String: String]?

    public init(params: [String: String]? = nil) {
        self.params = params
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case params
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(params, forKey: .params)
    }
}

