//
// GatewayCIoTConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GatewayCIoTConfig: Codable, JSONEncodable, Hashable {

    public var apn: String?
    public var udpEndpoint: String?
    public var coapEndpoint: String?

    public init(apn: String? = nil, udpEndpoint: String? = nil, coapEndpoint: String? = nil) {
        self.apn = apn
        self.udpEndpoint = udpEndpoint
        self.coapEndpoint = coapEndpoint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apn
        case udpEndpoint
        case coapEndpoint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(apn, forKey: .apn)
        try container.encodeIfPresent(udpEndpoint, forKey: .udpEndpoint)
        try container.encodeIfPresent(coapEndpoint, forKey: .coapEndpoint)
    }
}

