//
// Gateway.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A gateway is a connection between devices and Span */
public struct Gateway: Codable, JSONEncodable, Hashable {

    public var gatewayId: String?
    public var collectionId: String?
    public var networkId: String?
    public var tags: [String: String]?

    public init(gatewayId: String? = nil, collectionId: String? = nil, networkId: String? = nil, tags: [String: String]? = nil) {
        self.gatewayId = gatewayId
        self.collectionId = collectionId
        self.networkId = networkId
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gatewayId
        case collectionId
        case networkId
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gatewayId, forKey: .gatewayId)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(networkId, forKey: .networkId)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

