//
// GatewayDeviceConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Configuration parameters for a device in a user-managed gateway. The configuration parameters depends on the type of gateway. */
public struct GatewayDeviceConfig: Codable, JSONEncodable, Hashable {

    /** This is the ID of the gateway this configuration applies to. */
    public var gatewayId: String?
    public var params: [String: String]?

    public init(gatewayId: String? = nil, params: [String: String]? = nil) {
        self.gatewayId = gatewayId
        self.params = params
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gatewayId
        case params
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gatewayId, forKey: .gatewayId)
        try container.encodeIfPresent(params, forKey: .params)
    }
}

