//
// GatewayType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum GatewayType: String, Codable, CaseIterable {
    case unknown = "unknown"
    case ciot = "ciot"
    case inet = "inet"
    case lora = "lora"
    case openthread = "openthread"
    case zigbee = "zigbee"
    case matter = "matter"
    case custom = "custom"
}
