//
// GatewayMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Metadata for gateway transports. The actual contents varies from gateway to gateway */
public struct GatewayMetadata: Codable, JSONEncodable, Hashable {

    public var metadata: [String: String]?

    public init(metadata: [String: String]? = nil) {
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

