//
// GatewayCertificateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GatewayCertificateResponse: Codable, JSONEncodable, Hashable {

    public var certificates: [CertificateInfo]?

    public init(certificates: [CertificateInfo]? = nil) {
        self.certificates = certificates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case certificates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(certificates, forKey: .certificates)
    }
}

