//
// Gateway.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A gateway is a connection between devices and Span */
public struct Gateway: Codable, JSONEncodable, Hashable {

    public var gatewayId: String?
    public var collectionId: String?
    public var name: String?
    public var builtIn: Bool?
    public var type: GatewayType?
    public var config: GatewayConfig?
    public var tags: [String: String]?
    public var status: GatewayStatus?
    public var enabled: Bool?

    public init(gatewayId: String? = nil, collectionId: String? = nil, name: String? = nil, builtIn: Bool? = nil, type: GatewayType? = nil, config: GatewayConfig? = nil, tags: [String: String]? = nil, status: GatewayStatus? = nil, enabled: Bool? = nil) {
        self.gatewayId = gatewayId
        self.collectionId = collectionId
        self.name = name
        self.builtIn = builtIn
        self.type = type
        self.config = config
        self.tags = tags
        self.status = status
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gatewayId
        case collectionId
        case name
        case builtIn
        case type
        case config
        case tags
        case status
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gatewayId, forKey: .gatewayId)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(builtIn, forKey: .builtIn)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

