//
// ImageUploadReference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is a reference data structure for an uploaded firmware image */
public struct ImageUploadReference: Codable, JSONEncodable, Hashable {

    public var imageRef: String?
    public var createdAt: String?
    public var fileName: String?
    public var length: String?
    public var checksum: String?
    public var sha256: String?

    public init(imageRef: String? = nil, createdAt: String? = nil, fileName: String? = nil, length: String? = nil, checksum: String? = nil, sha256: String? = nil) {
        self.imageRef = imageRef
        self.createdAt = createdAt
        self.fileName = fileName
        self.length = length
        self.checksum = checksum
        self.sha256 = sha256
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case imageRef
        case createdAt
        case fileName
        case length
        case checksum
        case sha256
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(imageRef, forKey: .imageRef)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(fileName, forKey: .fileName)
        try container.encodeIfPresent(length, forKey: .length)
        try container.encodeIfPresent(checksum, forKey: .checksum)
        try container.encodeIfPresent(sha256, forKey: .sha256)
    }
}

