//
// ImageState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** State for a single image on a device */
public struct ImageState: Codable, JSONEncodable, Hashable {

    public var collectionId: String?
    public var deviceId: String?
    public var imageId: String?
    public var updated: String?
    public var state: String?
    public var message: String?

    public init(collectionId: String? = nil, deviceId: String? = nil, imageId: String? = nil, updated: String? = nil, state: String? = nil, message: String? = nil) {
        self.collectionId = collectionId
        self.deviceId = deviceId
        self.imageId = imageId
        self.updated = updated
        self.state = state
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionId
        case deviceId
        case imageId
        case updated
        case state
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(imageId, forKey: .imageId)
        try container.encodeIfPresent(updated, forKey: .updated)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

