//
// InlineObject1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct InlineObject1: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var collectionId: String?
    public var type: GatewayType?
    public var config: GatewayConfig?
    public var tags: [String: String]?

    public init(name: String? = nil, collectionId: String? = nil, type: GatewayType? = nil, config: GatewayConfig? = nil, tags: [String: String]? = nil) {
        self.name = name
        self.collectionId = collectionId
        self.type = type
        self.config = config
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case collectionId
        case type
        case config
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

