//
// ListDevicesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListDevicesResponse: Codable {

    public var devices: [Device]?

    public init(devices: [Device]? = nil) {
        self.devices = devices
    }

}
