//
// ListOutputResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List outputs */
public struct ListOutputResponse: Codable, JSONEncodable, Hashable {

    public var collectionId: String?
    public var outputs: [Output]?

    public init(collectionId: String? = nil, outputs: [Output]? = nil) {
        self.collectionId = collectionId
        self.outputs = outputs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionId
        case outputs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(outputs, forKey: .outputs)
    }
}

