//
// ListCollectionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Collection list. The list contains all the collections you have access to. */
public struct ListCollectionResponse: Codable, JSONEncodable, Hashable {

    public var collections: [Collection]?

    public init(collections: [Collection]? = nil) {
        self.collections = collections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collections
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collections, forKey: .collections)
    }
}

