//
// ListFirmwareResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListFirmwareResponse: Codable {

    public var images: [Firmware]?

    public init(images: [Firmware]? = nil) {
        self.images = images
    }

}
