//
// ListNetworkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List networks. */
public struct ListNetworkResponse: Codable, JSONEncodable, Hashable {

    public var networks: [Network]?

    public init(networks: [Network]? = nil) {
        self.networks = networks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case networks
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(networks, forKey: .networks)
    }
}

