//
// ListImageVersionHistoryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response obejct when listing image version log for a device */
public struct ListImageVersionHistoryResponse: Codable, JSONEncodable, Hashable {

    public var collectionId: String?
    public var log: [ImageVersionEntry]?

    public init(collectionId: String? = nil, log: [ImageVersionEntry]? = nil) {
        self.collectionId = collectionId
        self.log = log
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionId
        case log
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(log, forKey: .log)
    }
}

