//
// ListBlobResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response object when listing blobs for a collection */
public struct ListBlobResponse: Codable, JSONEncodable, Hashable {

    public var blobs: [Blob]?

    public init(blobs: [Blob]? = nil) {
        self.blobs = blobs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blobs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(blobs, forKey: .blobs)
    }
}

