//
// ListOutputResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListOutputResponse: Codable {

    public var collectionId: String?
    public var outputs: [Output]?

    public init(collectionId: String? = nil, outputs: [Output]? = nil) {
        self.collectionId = collectionId
        self.outputs = outputs
    }

}
