//
// ListDataResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListDataResponse: Codable {

    public var data: [OutputDataMessage]?

    public init(data: [OutputDataMessage]? = nil) {
        self.data = data
    }

}
