//
// MessageState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MessageState: String, Codable, CaseIterable {
    case unspecified = "unspecified"
    case pending = "pending"
    case sent = "sent"
    case failed = "failed"
}
