//
// MessageSendResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MessageSendResult: Codable {

    public var deviceId: String?
    public var message: String?

    public init(deviceId: String? = nil, message: String? = nil) {
        self.deviceId = deviceId
        self.message = message
    }

}
