//
// MQTTMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** MQTT metadata for messages received through one of the MQTT endpoints. This is an EXPERIMENTAL feature. */
public struct MQTTMetadata: Codable, JSONEncodable, Hashable {

    public var topic: String?

    public init(topic: String? = nil) {
        self.topic = topic
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case topic
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(topic, forKey: .topic)
    }
}

