//
// MultiSendMessageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Broadcast message result. The errors array contains the list of errors ocurred when sending a message. */
public struct MultiSendMessageResponse: Codable {

    public var errors: [MessageSendResult]?
    public var sent: Int?
    public var failed: Int?

    public init(errors: [MessageSendResult]? = nil, sent: Int? = nil, failed: Int? = nil) {
        self.errors = errors
        self.sent = sent
        self.failed = failed
    }

}
