//
// NetworkOperator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Operator holds information on the network operator. There might be several operators involved; one operator is running the network your devices are connected to and the SIM card in your device belongs to a different operator.  Deprecated: Replaced by CellularIoTMetadata */
public struct NetworkOperator: Codable, JSONEncodable, Hashable {

    /** The Mobile Country Code for the operator. */
    public var mcc: Int?
    public var mnc: Int?
    public var country: String?
    public var network: String?
    public var countryCode: String?

    public init(mcc: Int? = nil, mnc: Int? = nil, country: String? = nil, network: String? = nil, countryCode: String? = nil) {
        self.mcc = mcc
        self.mnc = mnc
        self.country = country
        self.network = network
        self.countryCode = countryCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mcc
        case mnc
        case country
        case network
        case countryCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mcc, forKey: .mcc)
        try container.encodeIfPresent(mnc, forKey: .mnc)
        try container.encodeIfPresent(country, forKey: .country)
        try container.encodeIfPresent(network, forKey: .network)
        try container.encodeIfPresent(countryCode, forKey: .countryCode)
    }
}

