//
// NetworkOperator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Operator holds information on the network operator. There might be several operators involved; one operator is running the network your devices are connected to and the SIM card in your device belongs to a different operator. */
public struct NetworkOperator: Codable {

    /** The Mobil Country Code for the operator. */
    public var mcc: Int?
    public var mnc: Int?
    public var country: String?
    public var network: String?
    public var countryCode: String?

    public init(mcc: Int? = nil, mnc: Int? = nil, country: String? = nil, network: String? = nil, countryCode: String? = nil) {
        self.mcc = mcc
        self.mnc = mnc
        self.country = country
        self.network = network
        self.countryCode = countryCode
    }

}
