//
// NetworkMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Network metadata for devices. */
public struct NetworkMetadata: Codable {

    /** Allocated IP address. */
    public var allocatedIp: String?
    public var allocatedAt: String?
    /** Cell ID for device. This might not be set, depending on the provider in use. */
    public var cellId: String?

    public init(allocatedIp: String? = nil, allocatedAt: String? = nil, cellId: String? = nil) {
        self.allocatedIp = allocatedIp
        self.allocatedAt = allocatedAt
        self.cellId = cellId
    }

}
