//
// Network.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Network is the network devices runs on. They communicate via gateway to Span. */
public struct Network: Codable, JSONEncodable, Hashable {

    public var networkId: String?
    public var tags: [String: String]?

    public init(networkId: String? = nil, tags: [String: String]? = nil) {
        self.networkId = networkId
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case networkId
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(networkId, forKey: .networkId)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

