//
// NetworkMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is the network metadata for a device. */
public struct NetworkMetadata: Codable, JSONEncodable, Hashable {

    /** Allocated IP address. */
    public var allocatedIp: String?
    public var allocatedAt: String?
    /** Cell ID for device. This might not be set, depending on the provider in use. */
    public var cellId: String?

    public init(allocatedIp: String? = nil, allocatedAt: String? = nil, cellId: String? = nil) {
        self.allocatedIp = allocatedIp
        self.allocatedAt = allocatedAt
        self.cellId = cellId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allocatedIp
        case allocatedAt
        case cellId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allocatedIp, forKey: .allocatedIp)
        try container.encodeIfPresent(allocatedAt, forKey: .allocatedAt)
        try container.encodeIfPresent(cellId, forKey: .cellId)
    }
}

