//
// OutputStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OutputStatusResponse: Codable {

    public var collectionId: String?
    public var outputId: String?
    public var enabled: Bool?
    public var errorCount: Int?
    public var forwarded: Int?
    public var received: Int?
    public var retransmits: Int?

    public init(collectionId: String? = nil, outputId: String? = nil, enabled: Bool? = nil, errorCount: Int? = nil, forwarded: Int? = nil, received: Int? = nil, retransmits: Int? = nil) {
        self.collectionId = collectionId
        self.outputId = outputId
        self.enabled = enabled
        self.errorCount = errorCount
        self.forwarded = forwarded
        self.received = received
        self.retransmits = retransmits
    }

}
