//
// OutputType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OutputType: String, Codable, CaseIterable {
    case undefined = "undefined"
    case webhook = "webhook"
    case udp = "udp"
    case mqtt = "mqtt"
    case ifttt = "ifttt"
}
