//
// OutputStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Statistics for a single data router */
public struct OutputStats: Codable, JSONEncodable, Hashable {

    public var forwardErrors: Int?
    public var messagesForwarded: String?
    public var bytesForwarded: String?

    public init(forwardErrors: Int? = nil, messagesForwarded: String? = nil, bytesForwarded: String? = nil) {
        self.forwardErrors = forwardErrors
        self.messagesForwarded = messagesForwarded
        self.bytesForwarded = bytesForwarded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case forwardErrors
        case messagesForwarded
        case bytesForwarded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(forwardErrors, forKey: .forwardErrors)
        try container.encodeIfPresent(messagesForwarded, forKey: .messagesForwarded)
        try container.encodeIfPresent(bytesForwarded, forKey: .bytesForwarded)
    }
}

