//
// OutputDataMessageOutputMessageType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OutputDataMessageOutputMessageType: String, Codable, CaseIterable {
    case unknown = "unknown"
    case keepalive = "keepalive"
    case data = "data"
}
