//
// Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Output: Codable {

    public var outputId: String?
    public var collectionId: String?
    public var type: OutputType?
    public var config: OutputConfig?
    public var enabled: Bool?
    public var tags: [String: String]?

    public init(outputId: String? = nil, collectionId: String? = nil, type: OutputType? = nil, config: OutputConfig? = nil, enabled: Bool? = nil, tags: [String: String]? = nil) {
        self.outputId = outputId
        self.collectionId = collectionId
        self.type = type
        self.config = config
        self.enabled = enabled
        self.tags = tags
    }

}
