//
// OutputLogEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Log entries for outputs */
public struct OutputLogEntry: Codable, JSONEncodable, Hashable {

    public var time: String?
    public var message: String?
    public var repeated: Int?

    public init(time: String? = nil, message: String? = nil, repeated: Int? = nil) {
        self.time = time
        self.message = message
        self.repeated = repeated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case time
        case message
        case repeated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(time, forKey: .time)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(repeated, forKey: .repeated)
    }
}

