//
// OutputConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Output configuration. */
public struct OutputConfig: Codable {

    public var url: String?
    public var basicAuthUser: String?
    public var basicAuthPass: String?
    public var customHeaderName: String?
    public var customHeaderValue: String?
    public var host: String?
    public var port: Int?
    public var key: String?
    public var eventName: String?
    public var asIsPayload: Bool?
    public var endpoint: String?
    /** MQTT configuration: Disable certificate checks. Default is off. */
    public var disableCertCheck: Bool?
    public var username: String?
    public var password: String?
    public var clientId: String?
    public var topicName: String?

    public init(url: String? = nil, basicAuthUser: String? = nil, basicAuthPass: String? = nil, customHeaderName: String? = nil, customHeaderValue: String? = nil, host: String? = nil, port: Int? = nil, key: String? = nil, eventName: String? = nil, asIsPayload: Bool? = nil, endpoint: String? = nil, disableCertCheck: Bool? = nil, username: String? = nil, password: String? = nil, clientId: String? = nil, topicName: String? = nil) {
        self.url = url
        self.basicAuthUser = basicAuthUser
        self.basicAuthPass = basicAuthPass
        self.customHeaderName = customHeaderName
        self.customHeaderValue = customHeaderValue
        self.host = host
        self.port = port
        self.key = key
        self.eventName = eventName
        self.asIsPayload = asIsPayload
        self.endpoint = endpoint
        self.disableCertCheck = disableCertCheck
        self.username = username
        self.password = password
        self.clientId = clientId
        self.topicName = topicName
    }

}
