//
// OutputStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Statistics for a single data router */
public struct OutputStats: Codable, JSONEncodable, Hashable {

    public var forwardErrors: Int?
    public var messagesForwarded: Int?
    public var bytesForwardedMb: Float?

    public init(forwardErrors: Int? = nil, messagesForwarded: Int? = nil, bytesForwardedMb: Float? = nil) {
        self.forwardErrors = forwardErrors
        self.messagesForwarded = messagesForwarded
        self.bytesForwardedMb = bytesForwardedMb
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case forwardErrors
        case messagesForwarded
        case bytesForwardedMb
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(forwardErrors, forKey: .forwardErrors)
        try container.encodeIfPresent(messagesForwarded, forKey: .messagesForwarded)
        try container.encodeIfPresent(bytesForwardedMb, forKey: .bytesForwardedMb)
    }
}

