//
// OutputType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Output types available   - undefined: The undefined output type is an invalid type */
public enum OutputType: String, Codable, CaseIterable {
    case undefined = "undefined"
    case webhook = "webhook"
    case udpout = "udpout"
    case mqttclient = "mqttclient"
    case ifttt = "ifttt"
    case mqttbroker = "mqttbroker"
}
