//
// OutputMessageType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum OutputMessageType: String, Codable, CaseIterable {
    case unknown = "unknown"
    case keepalive = "keepalive"
    case data = "data"
}
