//
// RetrieveBlobResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is not available throught the API, just as a regular HTTP response */
public struct RetrieveBlobResponse: Codable, JSONEncodable, Hashable {

    public var contentType: String?
    public var size: Int?
    public var data: Data?

    public init(contentType: String? = nil, size: Int? = nil, data: Data? = nil) {
        self.contentType = contentType
        self.size = size
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentType
        case size
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contentType, forKey: .contentType)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

