//
// SignCertificateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request certificate signing */
public struct SignCertificateRequest: Codable, JSONEncodable, Hashable {

    public var gatewayId: String?
    public var deviceId: String?
    public var csr: Data?

    public init(gatewayId: String? = nil, deviceId: String? = nil, csr: Data? = nil) {
        self.gatewayId = gatewayId
        self.deviceId = deviceId
        self.csr = csr
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gatewayId
        case deviceId
        case csr
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(gatewayId, forKey: .gatewayId)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(csr, forKey: .csr)
    }
}

