//
// UDPMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** UDP metadata for messages receveied through one of the UDP endpoints */
public struct UDPMetadata: Codable, JSONEncodable, Hashable {

    public var localPort: Int?
    public var remotePort: Int?

    public init(localPort: Int? = nil, remotePort: Int? = nil) {
        self.localPort = localPort
        self.remotePort = remotePort
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case localPort
        case remotePort
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(localPort, forKey: .localPort)
        try container.encodeIfPresent(remotePort, forKey: .remotePort)
    }
}

