//
// UDPMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UDPMetadata: Codable {

    public var localPort: Int?
    public var remotePort: Int?

    public init(localPort: Int? = nil, remotePort: Int? = nil) {
        self.localPort = localPort
        self.remotePort = remotePort
    }

}
