//
// UpdateFirmwareBody.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This is the request object when updating the firmware image */
public struct UpdateFirmwareBody: Codable, JSONEncodable, Hashable {

    public var collectionId: String?
    public var version: String?
    public var tags: [String: String]?
    public var enabled: Bool?

    public init(collectionId: String? = nil, version: String? = nil, tags: [String: String]? = nil, enabled: Bool? = nil) {
        self.collectionId = collectionId
        self.version = version
        self.tags = tags
        self.enabled = enabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionId
        case version
        case tags
        case enabled
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(enabled, forKey: .enabled)
    }
}

