//
// UpdateOutputRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request type to update outputs */
public struct UpdateOutputRequest: Codable, JSONEncodable, Hashable {

    public var collectionId: String?
    public var type: OutputType?
    public var config: OutputConfig?
    public var enabled: Bool?
    public var tags: [String: String]?

    public init(collectionId: String? = nil, type: OutputType? = nil, config: OutputConfig? = nil, enabled: Bool? = nil, tags: [String: String]? = nil) {
        self.collectionId = collectionId
        self.type = type
        self.config = config
        self.enabled = enabled
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collectionId
        case type
        case config
        case enabled
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collectionId, forKey: .collectionId)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

