//
// UpdateDeviceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateDeviceRequest: Codable {

    public var existingCollectionId: String?
    public var deviceId: String?
    /** The collection id for the device. This field is optional and can be omitted if the collection id isn&#39;t changed. When changing to a new collection you must be an owner of the other collection, ie an administrator of the team that owns the new collection. */
    public var collectionId: String?
    /** The IMSI is the unique ID for the (e|nu|whatever)SIM card on your device. This is the primary identifier for your device on the network. */
    public var imsi: String?
    /** The IMEI number is the unique ID for your hardware as seen by the network. Obviously you might have a completely different view on things. */
    public var imei: String?
    /** Tags are metadata for the device that you can set. These are just strings. */
    public var tags: [String: String]?
    public var firmware: FirmwareMetadata?

    public init(existingCollectionId: String? = nil, deviceId: String? = nil, collectionId: String? = nil, imsi: String? = nil, imei: String? = nil, tags: [String: String]? = nil, firmware: FirmwareMetadata? = nil) {
        self.existingCollectionId = existingCollectionId
        self.deviceId = deviceId
        self.collectionId = collectionId
        self.imsi = imsi
        self.imei = imei
        self.tags = tags
        self.firmware = firmware
    }

}
